spring:
  application:
    name: KataSpringBoot_3.1.2

  datasource:
    url: jdbc:mysql://localhost:3306/user_crud?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
